### ISSUE TITLE
Setup scheduled build

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Prca.Website#18]
We should setup a scheduled build to regularely build and publish the site.

**Comment by gep13** [comment]
@pascalberger I have went with this:

![image](https://cloud.githubusercontent.com/assets/1271146/24406320/f2e89c76-13bf-11e7-9f34-a1cc076171e4.png)

Which, by my understanding (https://github.com/atifaziz/NCrontab/wiki/Crontab-Expression), should be at 2300 every day.

Let me know if you want something different.

**Comment by gep13** [comment]
@pascalberger did you check to see if this ran last night?

**Comment by pascalberger** [comment]
@gep13 Yes it ran, but failed since it build `master`. I've changed it to `develop` being to default branch.

**Comment by gep13** [comment]
Doh! My bad 😄 

At least we know it ran.  Should we close this out, or wait for successful execution tonight?

**Comment by pascalberger** [comment]
I think it can be closed. Will check tomorrow if it now runs successfully
